version: 0.2

phases:
  install:
    commands:
      - "apt install unzip -y"
      - "wget https://releases.hashicorp.com/terraform/1.5.2/terraform_1.5.2_linux_amd64.zip"
      - "unzip terraform_1.5.2_linux_amd64.zip"
      - "mv terraform /usr/local/bin/"
      - "pwd"

  pre_build:
    commands:
      #- cd sdlf-stagea-infra
      - terraform init -backend-config="region=us-east-1" -backend-config="bucket=sancho-terraform-state" -backend-config="key=state/aws/sdlf/streams/terraform.tfstate"

  build:
    commands:
      - "pwd"
      - terraform fmt --recursive
      - terraform $TF_COMMAND -auto-approve -var-file="./_variables/prd.tfvars"
      #- terraform destroy -auto-approve -var-file="./_variables/prd.tfvars"
      
  post_build:
    commands:
      - echo Terraform $TF_COMMAND completed on `date`

      